### ISSUE TITLE
Terminalen burde se finere ut

### ISSUE THREAD

**Issue by Olav45** [OlavAase/MaOlOl#5]
termninalen burde se finere ut sånn at spilleren lettere kan skjønne hvor mange terninger det er igjen totalt, hvilken runde det er og tydliggjøre hvilke actions computeren gjør

**Comment by Magnus44** [comment]
har gjort det mer forståelig med litt Delay og sånt så ikke all info spammes ut med en gang. det skal være lettere å få med seg hva som skjer. i tillegg la jeg til en knapp som gjør at man selv styrer når man går videre til neste gjett.
